version: '3.8'
services:
  evenement:
    build: ./EvenementLocation
    container_name: evenement
    restart: always
    ports:
     - "443:443"
    networks:
      - ludotheque
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak-ludotheque
    ports:
     - "8080:8080"
    command:
      - "start-dev"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    environment:
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb-ludotheque
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=2000
    restart: always
    depends_on:
      - mariadb-dev
    networks:
      - ludotheque
  mariadb-dev:
    image: mariadb
    container_name: mariadb-ludotheque
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
    ports:
     - "3306:3306"
    restart: always
    networks:
      - ludotheque
    volumes:
      - mariadb-data:/var/lib/mysql/data
  mongo:
    image: mongo:5.0
    container_name: mongo-ludotheque
    #ports:
    #  - "27017:27017"
    restart: always
    networks:
      - ludotheque
    volumes:
      - mongo-data:/data/db
volumes:
  mariadb-data:
    name: mariadb-ludotheque-data
    driver: local
  mongo-data:
    name: mongo-evenement-data
    driver: local
networks:
  ludotheque:
    name: ludotheque
